apiVersion: v1
kind: Service
metadata:
  name: mon-app-service
spec:
  selector:
    app: deep  # Sélectionne les pods avec l'étiquette "app: mon-app"
  ports:
    - protocol: TCP
      port: 5000  # Port du service
      targetPort: 5000  # Port cible des pods
  type: LoadBalancer   # Type de service (ClusterIP pour un accès interne au cluster)
